### ISSUE TITLE
Port plugin to TypeScript

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/jsdoc-typescript-plugin#18]
As this plugin starts to flesh out in functionality, it's becoming clearer that I desire the object-orientedness and type safety of TypeScript when implementing new support and features.

So let's pause for a moment and port everything we currently have to TypeScript

**Comment by icholy** [comment]
I was a little surprised when I saw it wasn't :stuck_out_tongue_winking_eye:

**Comment by jumpinjackie** [comment]
@icholy lol yeah.
