### ISSUE TITLE
naive union type processing

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/jsdoc-typescript-plugin#55]
Currently, the type processing for these types naively splits on the `|` character and processes the individual bits. 

Cesium.js has a method where the type is the following:

`Entity|Entity[]|EntityCollection|DataSource|ImageryLayer|Promise.<Entity|Entity[]|EntityCollection|DataSource|ImageryLayer>`

and the current type processing renders an incorrectly translated type for this method

**Comment by icholy** [comment]
Relates to #54. Needs a parser.

**Comment by jumpinjackie** [comment]
Fixed thanks to @lRawd pull request (#83)
